### ISSUE TITLE
Make chunkSize setting overridable

### ISSUE THREAD

**Issue by EllisShen** [rasmuslp/angular-file-md5#3]
Hi Ljungmann,

Thanks for the public your angulrJs based MD5 module. I'm using it to calculate hash number of large video file. I suggest to define the **chunkSize** using _value service_, so that the setting can be overridden by application.

Best regards,
Ellis Shen

**Comment by rasmuslp** [comment]
Hi Ellis,

It is already possible to override the default chunkSize by configuring the provider like this:

```
angular.module('your.module', ['ljungmann.fileMd5'])

.config(['fileMd5ServiceProvider', function(fileMd5ServiceProvider) {
  fileMd5ServiceProvider.configure({
    chunkSize: <set-size-in-bytes-here>
  });
}]);
```

Is this sufficient for your needs?

NB: The above code is _not_ tested but should work.

**Comment by EllisShen** [comment]
Hi Ljungmann,
oh, that's right. It should work. I'll close the issue then.
Thanks!
